package com.bookmyride.fcm;

/**
 * Created by vinod on 1/20/2017.
 */
public interface NotificationFilters {
    //String INCOMING_RIDE_REQUEST = "ACTION_INCOMING_RIDE_REQUEST";
    String DRIVER_ARRIVED = "ACTION_DRIVER_ARRIVED";
    String BEGIN_RIDE = "ACTION_BEGIN_RIDE";
    String END_RIDE = "ACTION_END_RIDE";
    String RIDE_ACCEPTED = "ACTION_RIDE_ACCEPTED";
    String RIDE_DECLINED = "ACTION_RIDE_DECLINED";
    String PAYMENT_REQEUST = "ACTION_PAYMENT_REQUEST";
    String AVAILABLE_RIDE = "ACTION_AVAILABLE_RIDES";
    String AVAILABLE_BOOKINGS = "ACTION_AVAILABLE_BOOKINGS";

    String REQUEST_CANCELLED = "ACTION_REQUEST_CANCELLED";
    String LOCATION_CHANGED = "ACTION_LOCATION_CHANGED";
    String UPDATE_STATUS = "ACTION_STATUS_CHANGED";
    String PAYMENT_PENDING = "ACTION_PAYMENT_PENDING";

}
